# 网吧经营系统配置

# 基础设置
base:
  initial_money: 50000
  max_level: 5
  credit_initial: 100
  daily_decay: 0.5

# 经营参数
business:
  hourly_rate:
    basic: 5
    standard: 8
    premium: 12
  maintenance_cost:
    basic: 80
    standard: 120
    premium: 200
  staff_max_satisfaction: 100
  customer_max_satisfaction: 100
  reputation_max: 100
  cleanliness_decay: 1
  equipment_decay: 0.5

# 员工系统
staff:
  max_work_hours: 8
  overtime_rate: 1.5
  training_effectiveness: 1.2
  satisfaction_bonus: 0.1
  performance_bonus: 0.2
  max_employees_per_level: 3

# VIP包间
vip_room:
  max_rooms_per_level: 2
  cleanliness_requirement: 80
  maintenance_requirement: 85
  staff_requirement: 1
  booking_advance_hours: 24
  minimum_hours: 1
  maximum_hours: 12
  deposit_rate: 0.3

# 餐饮服务
food_service:
  storage_capacity: 1000
  restock_threshold: 20
  freshness_days: 7
  spoilage_rate: 0.05
  profit_margin_min: 0.2
  profit_margin_max: 0.5
  service_fee: 0.1

# 会员系统
membership:
  levels:
    normal:
      discount: 0.9
      points_rate: 1
      requirements: 0
    silver:
      discount: 0.8
      points_rate: 1.2
      requirements: 1000
    gold:
      discount: 0.7
      points_rate: 1.5
      requirements: 5000
    diamond:
      discount: 0.6
      points_rate: 2
      requirements: 20000
  points_per_spend: 1
  points_expire_days: 365
  birthday_bonus: 500

# 活动系统
events:
  tournament:
    small:
      cost: 5000
      prize: 2000
      duration: 24
      min_participants: 8
    medium:
      cost: 15000
      prize: 8000
      duration: 48
      min_participants: 16
    large:
      cost: 50000
      prize: 30000
      duration: 72
      min_participants: 32
  promotion:
    holiday:
      discount: 0.8
      duration: 72
      customer_increase: 1.5
    midnight:
      special_price: 20
      duration: 24
      customer_increase: 1.3
    student:
      discount: 0.7
      hours: ["14:00", "17:00"]
      customer_increase: 1.2

# 装修系统
decoration:
  styles:
    basic:
      cost: 20000
      duration: 2880
      effects:
        reputation: 5
        satisfaction: 5
    netcafe:
      cost: 50000
      duration: 4320
      effects:
        reputation: 10
        satisfaction: 10
    esports:
      cost: 100000
      duration: 5760
      effects:
        reputation: 20
        satisfaction: 15
    luxury:
      cost: 200000
      duration: 7200
      effects:
        reputation: 30
        satisfaction: 20
  maintenance_cost_rate: 0.01
  decay_rate: 0.1

# 广告系统
advertising:
  types:
    flyer:
      base_effect: 1
      duration_hours: 24
      coverage: 100
    online:
      base_effect: 1.5
      duration_hours: 72
      coverage: 500
    media:
      base_effect: 2
      duration_hours: 168
      coverage: 1000
    event:
      base_effect: 2.5
      duration_hours: 48
      coverage: 300
  min_investment: 1000
  effect_multiplier: 0.001
  reputation_gain_rate: 0.1

# 贷款系统
loan:
  types:
    short:
      max_amount: 100000
      interest_rate: 0.1
      duration_days: 7
      credit_requirement: 60
    medium:
      max_amount: 500000
      interest_rate: 0.15
      duration_days: 30
      credit_requirement: 70
    long:
      max_amount: 1000000
      interest_rate: 0.2
      duration_days: 90
      credit_requirement: 80
  credit_penalty_rate: 5
  max_loans: 1
  early_repayment_discount: 0.1

# 统计系统
statistics:
  peak_hours_threshold: 0.8
  occupancy_rate_good: 0.7
  equipment_usage_good: 0.8
  customer_satisfaction_good: 0.8
  profit_margin_good: 0.2
  report_items: 30

# 随机事件
random_events:
  probability: 0.1
  max_daily: 3
  types:
    positive:
      weight: 0.4
      min_effect: 0.05
      max_effect: 0.2
    neutral:
      weight: 0.3
      min_effect: -0.1
      max_effect: 0.1
    negative:
      weight: 0.3
      min_effect: -0.2
      max_effect: -0.05

# 环境系统
environment:
  temperature:
    optimal: 25
    tolerance: 3
    effect_rate: 0.1
  noise:
    max: 70
    effect_rate: 0.05
  air_quality:
    min: 60
    effect_rate: 0.1
  lighting:
    optimal: 80
    effect_rate: 0.05

# 奖励系统
rewards:
  daily_login: 100
  level_up: 1000
  perfect_service: 500
  event_completion: 200
  membership_upgrade: 300